/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ['node-0']: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
  };
};
type ModelProps = {
  ref?: React.Ref<THREE.Group>;
} & JSX.IntrinsicElements['group'];

export default function Model({ ref, ...props }: ModelProps) {
  const { nodes, materials } = useGLTF('/three/PaperAirplane.glb') as
    | GLTFResult
    | any;

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes['node-0'].geometry} material={materials.White} />
    </group>
  );
}

useGLTF.preload('/three/PaperAirplane.glb');
