services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:8080}
      - SERVER_URI=${SERVER_URI:-http://localhost:8080}
    env_file:
      - ./.env
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        GO_ENV: development
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - ./server:/server
    environment:
      - GIN_MODE=debug
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET:-secret}
      - FRONTEND_URI=${FRONTEND_URI:-http://localhost:3000}
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-chatapp}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./.env

volumes:
  postgres_data:
  redis_data:
