root = "."
tmp_dir = "tmp"
[build]
  bin = "./tmp/api"
  cmd = "go run scripts/migrations/run.go && go mod download && go build -ldflags \"-X main.serverHost=0.0.0.0\" -o ./tmp/api ./cmd/api/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = true
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
[log]
  time = false
[misc]
  clean_on_exit = false
