FROM golang:latest
WORKDIR /server
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Expose port
EXPOSE 8080
# Set environment variable for binding address
ENV GIN_HOST=0.0.0.0
# Build and run the application
CMD ["sh", "-c", "go run -ldflags \"-X main.serverHost=0.0.0.0\" ./cmd/api/main.go"]
